stages:
  - build

variables:
  CONTAINER_IMAGE: ergw/vpp
  CI_REGISTRY: index.docker.io  # container registry URL
  CI_REGISTRY_IMAGE: https://index.docker.io/v1/


# build container image
.build:
  stage: build
  #tags:
  #  - docker
  image: docker:git
  services:
  - docker:dind
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - echo "Docker HUB login..."
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - echo "Building the image from $DOCKER_FILE ..."
    - DOCKER_BUILDKIT=1 docker build -t ${CONTAINER_IMAGE_BUILT} -f ${DOCKER_FILE} .
    - docker push ${CONTAINER_IMAGE_BUILT}

# build container image
build:release:
  extends: .build
  variables:
    DOCKER_FILE: extras/docker/Dockerfile
    CONTAINER_IMAGE_BUILT: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}

build:debug:
  extends: .build
  variables:
    DOCKER_FILE: extras/docker/Dockerfile.devel
    CONTAINER_IMAGE_BUILT: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}_debug
