stages:
  - build

variables:
  CONTAINER_IMAGE: ergw/vpp
  CONTAINER_IMAGE_BUILT: ${CONTAINER_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHA}
  CONTAINER_IMAGE_LATEST: ${CONTAINER_IMAGE}:latest
  CI_REGISTRY: index.docker.io  # container registry URL
  CI_REGESTRY_IMAGE: https://index.docker.io/v1/


# build container image
build:
  stage: build
  #tags: 
  #  - docker
  image: docker:git
  services:
  - docker:dind
  script:
    - export DOCKER_HOST="tcp://localhost:2375"
    - echo "Docker HUB login..."
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - echo "Building the production image..."
    - DOCKER_BUILDKIT=1 docker build --target release -t ${CONTAINER_IMAGE_BUILT} -f extras/docker/Dockerfile .
    - docker push ${CONTAINER_IMAGE_BUILT}
    - echo "Building the debug image..."
    - DOCKER_BUILDKIT=1 docker build --target debug -t ${CONTAINER_IMAGE_BUILT}_debug -f extras/docker/Dockerfile .
    - docker push ${CONTAINER_IMAGE_BUILT}_debug
